name: Repopack Workflow

on:
  push:
    branches:
      - main

jobs:
  repopack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Repopack
        run: npm install -g repopack

      - name: Run Repopack
        run: repopack --remote https://github.com/your_username/your_repo.git

      - name: Upload repopack output
        uses: actions/upload-artifact@v2
        with:
          name: repopack-output
          path: ./repopack-output.txt
