name: Repopack Automation

on:
  push:
    branches:
      - main

jobs:
  repopack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Repopack
        run: npm install -g repopack
      - name: List Directory
        run: ls -R
      
      # Use relative path for the preprocessing script
      - name: Run Preprocessing Script
        run: python magic_machine_app/preprocess_repopack.py

      - name: Upload Session Summaries
        uses: actions/upload-artifact@v3
        with:
          name: session-summaries
          path: magic_machine_app/session_summaries.txt

      - name: Upload Optimized Output
        uses: actions/upload-artifact@v3
        with:
          name: optimized-repopack-output
          path: ./optimized-repopack-output.xml
