name: Repopack Automation

on:
  push:
    branches:
      - main

jobs:
  repopack:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js v20
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install Repopack globally
      - name: Install Repopack
        run: npm install -g repopack

      # Verify repository access
      - name: Verify Repository Access
        run: git ls-remote https://github.com/tylermontell/magic_machine.git

      # Step 4: Run Repopack and Generate Output
      - name: Run Repopack and Generate Output
        run: |
          repopack --config repopack.config.json
          ls -l

      # Step 5: Run Preprocessing Script if repopack-output.xml exists
      - name: Run Preprocessing Script
        if: success()
        run: python preprocess_repopack.py

      # Step 6: Commit and push the optimized output back to the repository
      - name: Commit and Push Optimized Output
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "GitHub Action"
          git add optimized-repopack-output.xml
          git commit -m "Auto-commit optimized repopack output"
          git push origin main

      # Step 7: Upload session summaries as artifacts
      - name: Upload Session Summaries
        uses: actions/upload-artifact@v3
        with:
          name: session-summaries
          path: session_summaries.txt

      # Step 8: Upload optimized repopack output as artifacts
      - name: Upload Optimized Output
        uses: actions/upload-artifact@v3
        with:
          name: optimized-repopack-output
          path: ./optimized-repopack-output.xml

      # Step 9: Upload optimized repopack output as artifacts
      - name: Upload Optimized Output
        uses: actions/upload-artifact@v3
        with:
          name: optimized-repopack-output
          path: ./optimized-repopack-output.xml
      
      # Step 10: Commit and push the optimized output back to the repository
      - name: Commit and Push Optimized Output
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "GitHub Action"
          git add optimized-repopack-output.xml
          git commit -m "Auto-commit optimized repopack output"
          git push origin main
